### ISSUE TITLE
Order of items in version list is not defined 

### ISSUE THREAD

**Issue by airstruck** [airstruck/love-wiki-version-picker#1]
The `injectVersionTags` function injects versions into the picker. It uses `for .. in` which doesn't iterate in a predicable order. When iterating properties of an object that was defined as an object literal, most implementations will iterate the in the same order the properties were defined, but this isn't guaranteed. Should change back to pulling the version page with XHR or store versions in an array instead of a plain object.

**Comment by airstruck** [comment]
@bartbes do you still prefer a hard coded list over pulling the version page via XHR?

**Comment by bartbes** [comment]
I do.

**Comment by airstruck** [comment]
I'll let you handle it then.

**Comment by airstruck** [comment]
@bartbes arrays have the same problem with `for..in`, needs a C-style `for` construct or `Array#forEach`. Latest (untested) commit should fix it. Just reopening this until change makes it live.

**Comment by bartbes** [comment]
I'm sorry, I confused javascript with a sane language,

**Comment by airstruck** [comment]
It's pretty much the same issue `pairs` has in Lua. Most implementations will iterate in ascending order, there's just no guarantee. The real insanity happens when someone decides to augment Object.prototype or Array.prototype with some enumerable properties. Pre-ES5, you'd usually see `hasOwnProperty` used with `for..in` as a defensive measure against that; post-ES5 you see a lot of `Object.keys` and `forEach` in place of `for` constructs. Anyway, I guess it's relatively sane as long as you avoid the stuff with poorly defined behavior.
